#!/bin/sh

# This program and the accompanying materials are made available under the
# terms of the MIT license (X11 license) which accompanies this distribution.
# 
# Author: Christoff Bürger

script_directory="$(cd "$(dirname "$0")"; pwd)"
cd "$script_directory/../Resources/pmChess/bin"
./pmChess $@
